INSERT INTO contributions (contribution_text, status, created_on, votes, contributor_id, story_id)
VALUES ('Godfather ipsum dolor sit amet. In Sicily, women are more dangerous than shotguns. Friends and money - oil and water. If anything in this life is certain, if history has taught us anything, it is that you can kill anyone. What''s wrong with being a lawyer? It''s not personal. It''s business.', 'In Progress', '2020-01-31', 5, 1, 1),
('Godfather ipsum dolor sit amet. In Sicily, women are more dangerous than shotguns. Friends and money - oil and water. If anything in this life is certain, if history has taught us anything, it is that you can kill anyone. What''s wrong with being a lawyer? It''s not personal. It''s business.', 'In Progress', '2021-10-19', 4, 4, 2),
('Find peace, life is like a water fall, you’ve gotta flow. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. You smart, you loyal, you a genius. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise. Hammock talk come soon. Wraith talk. Always remember in the jungle there’s a lot of they in there, after you overcome they, you will make it to paradise.', 'In Progress', '2021-10-19', 4, 4, 2),
('You do know, you do know that they don’t want you to have lunch. I’m keeping it real with you, so what you going do is have lunch. You do know, you do know that they don’t want you to have lunch. I’m keeping it real with you, so what you going do is have lunch. Stay focused. The key is to drink coconut, fresh coconut, trust me. Life is what you make it, so let’s make it. It’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean.', 'In Progress', '2021-10-19', 5, 3, 6),
('Leave fur on owners clothes catch mouse and gave it as a present plan steps for world domination but mewl for food at 4am poop in litter box, scratch the walls i heard this rumor where the humans are our owners, pfft, what do they know?! and missing until dinner time. Pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now caticus cuteicus so shred all toilet paper and spread around the house somehow manage to catch a bird but have no idea what to do next, so play with it until it dies of shock. Rub butt on table meow slap owner''s face at 5am until human fills food dish but sit by the fire yet cats go for world domination i bet my nine lives on you-oooo-ooo-hooo leave hair everywhere. Cereal boxes make for five star accommodation cereal boxes make for five star accommodation stares at human while pushing stuff off a table destroy house in 5 seconds. Steal mom''s crouton while she is in the bathroom love me! why dog in house? i''m the sole ruler of this home and its inhabitants smelly, stupid dogs, inferior furballs time for night-hunt, human freakout for bite off human''s toes lick left leg for ninety minutes, still dirty or find empty spot in cupboard and sleep all day go into a room to decide you didn''t want to be in there anyway. Refuse to leave cardboard box sit on human and this cat happen now, it was too purr-fect!!! and spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce. If it fits i sits i is not fat, i is fluffy, or leave hair on owner''s clothes i want to go outside let me go outside nevermind inside is better and murder hooman toes hate dogs. Jump five feet high and sideways when a shadow moves kitty time pee on walls it smells like breakfast side-eyes your "jerk" other hand while being petted for mrow for destroy the blinds. Meowing chowing and wowing haha you hold me hooman i scratch cats are cute and sleep on dog bed, force dog to sleep on floor.', 'In Progress', '2021-01-25', 10, 4, 7),
('Protein, iron, and calcium are some of the nutritional benefits associated with cheeseburgers. Salad is essentially food for rabbits, so don’t bother wasting your time.', 'In Progress', '2020-02-11', 4, 6, 13),
('There’s cheesy incarnation waiting for you no matter what your palate preferences are. Unless you’re vegan, in which case we’re sorry for your loss.', 'In Progress', '2021-03-29', 19, 9, 15),
('Finally, cheeseburgers are incapable of telling lies or hurting you. On the flip side, they can still Rick Roll you.', 'In Progress', '2021-07-23', 25, 2, 6),
('Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.', 'In Progress', '2021-06-06', 6, 6, 9),
('Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.', 'In Progress', '2021-06-06', 60, 11, 17),
('Lorizzle owned sit amizzle, consectetuer adipiscing elizzle. Nullam sapien velizzle, aliquet hizzle, suscipizzle gangsta, stuff vel, arcu. Pellentesque fizzle fo shizzle. Sed erizzle. Dang at dapibizzle turpizzle uhuh ... yih! tempizzle. Maurizzle pellentesque nibh i''m in the shizzle turpis. Go to hizzle dizzle tortizzle. Pellentesque the bizzle rhoncus nisi. In hac habitasse platea dictumst. For sure dapibus. Fo shizzle tellizzle urna, pretizzle fo shizzle, mattis izzle, tellivizzle vitae, nunc. That''s the shizzle suscipizzle. Fo nizzle velizzle sizzle check out this.', 'In Progress', '2021-09-13', 0, 3, 5),
('Your bones don''t break, mine do. That''s clear. Your cells react to bacteria and viruses differently than mine. You don''t get sick, I do. That''s also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I.', 'In Progress', '2019-08-12', 2, 1, 18),
('Mahseer longjaw mudsucker dottyback goby haddock cutthroat eel angler catfish riffle dace skilfish squaretail plunderfish: bluefish. Hussar redtooth triggerfish soapfish Red salmon shovelnose sturgeon, jewel tetra medaka staghorn sculpin pikeperch herring swordtail. Viperfish squeaker flier, Atlantic salmon razorfish drum Black scalyfin. Tope jackfish frigate mackerel North American darter yellowfin croaker dottyback. Salmon shark Atlantic eel stingray weeverfish gunnel. Herring smelt requiem shark lake chub red velvetfish.', 'In Progress', '2021-08-12', 7, 3, 7),
('Catalufa, tiger shark pike conger false trevally, New Zealand smelt zander. Dealfish trout spinefoot garden eel seatrout; molly Rio Grande perch bluefin tuna Arctic char cardinalfish yellowfin tuna. Horn shark conger eel white marlin. Livebearer Moorish idol bristlenose catfish three spot gourami, gudgeon halfbeak pickerel glass knifefish, sabertooth fish pollock tidewater goby. Torpedo whalefish dace stingfish gulf menhaden bobtail snipe eel knifejaw lemon shark.', 'In Progress', '2021-05-15', 19, 5, 9),
('Marblefish longnose dace butterfly ray sockeye salmon galjoen fish pearl danio sleeper shark pencilfish. Mullet dragonfish, ziege chubsucker sixgill ray Reef triggerfish, sharksucker codling freshwater eel spiny basslet pigfish Ragfish cownose ray. ', 'In Progress', '2021-04-15', 19, 9, 19);




